manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: boards/ferris-02-bling-basics
      import: app/west.yml
  self:
    path: config
